# This config file is meant for setting up an override to localhost:4000/
# Run using jekyll serve with -config option to place this one in the list
baseurl: "" # the subpath of your site, e.g. /blog
